name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - feature/aws-eb-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deployment
          cp -R dist node_modules package.json package-lock.json deployment/
          cd deployment
          zip -r ../deploy.zip .

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: 'us-east-1'
        run: |
          aws s3 cp deploy.zip s3://$S3_BUCKET/deploy.zip
          aws elasticbeanstalk create-application-version --application-name photo-sharing-api-v2 --version-label $GITHUB_SHA --source-bundle S3Bucket=$S3_BUCKET,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --application-name photo-sharing-api-v2 --environment-name photo-sharing-api-v2-env --version-label $GITHUB_SHA