name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - feature/aws-eb-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          zip -r deploy.zip .
          aws elasticbeanstalk create-application-version --application-name photo-sharing-api --version-label $GITHUB_SHA --source-bundle S3Bucket=$S3_BUCKET,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --application-name photo-sharing-api --environment-name photo-sharing-api-env --version-label $GITHUB_SHA